export const languages = {
  en: {
    muscles: {
      deltoids: "Shoulders",
      biceps: "Biceps",
      obliques: "Obliques",
      abductors: "Abductors",
      quadriceps: "Quads",
      chest: "Chest",
      abs: "Abs",
      forearm: "Forearm",
      adductors: "Adductors",
      trapezius: "Traps",
      "upper-back": "Lats",
      triceps: "Triceps",
      "lower-back": "Lower Back",
      gluteal: "Glutes",
      hamstring: "Hamstrings",
      calves: "Calves",
      cardio: "Cardio",
    },
    nav: {
      dashboard: "Dashboard",
      atlas: "Neural Atlas",
      workouts: "Workouts",
      history: "History",
      analytics: "Analytics",
      settings: "Settings",
      signOut: "Sign Out",
      level: "Level",
    },
    ui: {
      welcome: "Welcome",
      efficiency: "Operational Efficiency",
      tier: "Tier 07 Operator",
      scanner: "Initialize Scanner",
      selectMuscle: "Select a muscle group from the atlas to identify compatible movements.",
      database: "Accessing Database...",
      difficulty: "Difficulty",
      search: "Search for exercises...",
      routines: "Tactical Routines",
      viewAll: "View All",
      intermediate: "Intermediate",
      units: "Units",
      min: "Min",
      activeSession: "Active Session",
      formatTime: "recorded",
      payload: "Payload",
      repetitions: "Repetitions",
      register: "Register Performance",
      sessionHistory: "Session History",
      telemetry: "Live Telemetry",
      terminate: "Terminate",
      objective: "Current Objective",
      returnBase: "Return to Base",
      returnCommand: "Return to Command",
      anterior: "Anterior",
      posterior: "Posterior",
      musculature: "Musculatura",
      core: "Core",
      equipment: "Equipment",
      selectEquipment: "Select Available Equipment",
      saveSession: "Save Session",
      discardSession: "Discard Session",
      confirmDiscard: "Are you sure you want to discard this session? All progress will be lost.",
      deleteConfirm: "Are you sure you want to delete this session?",
      confirm: "Confirm",
      cancel: "Cancel",
    },
    equipment: {
      bodyweight: "Bodyweight",
      barbell: "Barbell",
      dumbbell: "Dumbbell",
      machine: "Machine / Cables",
      plate: "Plate",
      bench: "Bench",
      kettlebell: "Kettlebell",
      band: "Resistance Band",
      ab_wheel: "Ab Wheel",
    },
    stats: {
      recovery: "Biometric Recovery",
      intensity: "Session Intensity",
      load: "Accumulated Load",
    },
    auth: {
      loginTitle: "Authentication",
      registerTitle: "Operator Registry",
      loginDesc: "Secure access to your training intelligence.",
      registerDesc: "Initialize your evolution with FitAtlas intelligence.",
      fullName: "Full Name",
      email: "Communications Link",
      password: "Encryption Key",
      initiate: "Initiate Session",
      finalize: "Finalize Registry",
      newOperator: "Register New Operator",
      existingIntel: "Access Existing Intel",
      namePlaceholder: "Operator Name",
      emailPlaceholder: "operator@fitatlas.ai",
    },
    landing: {
      badge: "FitAtlas 2.0 Alpha — Now Live",
      title: "STOP TRAINING. EVOLVE.",
      subtitle: "The world's most sophisticated training intelligence. Bio-visual muscle mapping, intelligent stress analysis, and RPG-inspired progression.",
      getStarted: "Start Your Evolution",
      manifesto: "The Manifesto",
      atlasTitle: "Neural Atlas",
      atlasDesc: "Interactive biomechanical muscle mapping for surgical exercise precision.",
      stressTitle: "Stress Engine",
      stressDesc: "Real-time mechanical tension calculations and volume distribution.",
      rpgTitle: "RPG Progression",
      rpgDesc: "Gamified attribute leveling and adaptive training recommendations.",
      privacy: "Privacy",
      terms: "Terms",
      support: "Support",
      footer: "Crafted for the top 1%.",
    },
    about: {
      title: "Training for the New Age.",
      subtitle: "FitAtlas is not just a tracker. It is a biological intelligence engine designed to bridge the gap between human effort and algorithmic precision.",
      dnaTitle: "Our DNA",
      dnaDesc: "We believe that every repetition is data. By visualizing the mechanical tension distributed across your anatomy, we provide the insights needed to reach peak physiological optimization.",
      goalTitle: "The Goal",
      goalDesc: "Eliminate the guesswork. Whether you are a professional operator or a dedicated enthusiast, FitAtlas provides the tactical roadmap to your ultimate evolution.",
      pillarsTitle: "Operational Pillars",
      p1Title: "Integrity",
      p1Desc: "Scientific accuracy in every biomechanical calculation.",
      p2Title: "Efficiency",
      p2Desc: "Maximizing output while optimizing recovery windows.",
      p3Title: "Precision",
      p3Desc: "Targeted muscle isolation through visual mapping.",
      visionTitle: "Join the Elite.",
      visionDesc: "We are building the future of physical intelligence. Be part of the first generation of athletes training with the power of the Atlas.",
      visionBtn: "Initialize Evolution",
    },
    routines: {
      managerTitle: "Tactical Command",
      createBtn: "Initialize Routine",
      editBtn: "Modify",
      deleteBtn: "Purge",
      startBtn: "Initiate",
      emptyState: "No tactical routines identified. Initialize your first protocol.",
      editorTitle: "Protocol Architect",
      saveBtn: "Save Routine",
      addExercise: "Add Objective",
      routineName: "Routine Designation",
      difficulty: "Strain Level",
      blocks: "Blocks",
      sets: "Sets",
      reps: "Reps",
      weight: "Weight (kg)",
      time: "Time (min)",
      superset: "Superset Protocol",
      restPeriod: "Rest Duration",
      restAfterSuperset: "Rest After Superset",
      addSuperset: "Initialize Superset",
      exerciseType: "Modality",
    },
    analytics: {
      title: "Performance Intel",
      subtitle: "Real-time performance and recovery biomechanics",
      totalSessions: "Total Sessions",
      totalPayload: "Total Payload",
      avgIntensity: "Avg Intensity",
      efficiency: "Efficiency",
      performanceDelta: "Performance Delta",
      volume: "Volume",
      insufficientData: "Insufficient data for performance visualization",
      focusDistribution: "Focus Distribution",
      balanceWarning: "Your primary focus remains on the anterior chain. Consider increasing posterior volume for biomechanical balance.",
      balanceGood: "Your distribution is balanced. Maintain this ratio to prevent postural adaptations.",
      recoveryMap: "Neural Recovery Map",
      recoverySubtitle: "Estimated muscle fatigue based on training history",
      recovered: "Recovered",
      lightFatigue: "Light Fatigue",
      moderateFatigue: "Moderate",
      highFatigue: "High Fatigue",
      howItWorksTitle: "How it works",
      howItWorksDesc: "The recovery engine calculates local muscle fatigue using an exponential decay model (T½ ≈ 24h). High intensity sessions (RPE 9-10) generate greater fatigue and require longer windows. Training \"Red\" muscles significantly increases injury risk and CNS burnout.",
    },
    settings: {
      title: "Control Panel",
      subtitle: "Configure your operator profile and preferences",
      profile: "Profile Information",
      language: "System Language",
      name: "Operator Name",
      email: "Comms Link",
      password: "New Encryption Key",
      currentPassword: "Current Key",
      save: "Apply Changes",
      success: "Profile updated successfully",
      error: "Error updating profile",
    },
    difficulty: {
      very_easy: "Very Easy",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      elite: "Elite",
      epic: "Epic",
    },
    misc: {
      noData: "No data",
      mixedProtocol: "Mixed Protocol",
    }
  },
  es: {
    muscles: {
      deltoids: "Hombros",
      biceps: "Bíceps",
      obliques: "Oblicuos",
      abductors: "Abductores",
      quadriceps: "Cuádriceps",
      chest: "Pectorales",
      abs: "Abdomen",
      forearm: "Antebrazo",
      adductors: "Aductores",
      trapezius: "Trapecio",
      "upper-back": "Dorsales",
      triceps: "Tríceps",
      "lower-back": "Lumbares",
      gluteal: "Glúteos",
      hamstring: "Isquiotibiales",
      calves: "Pantorrillas",
      cardio: "Cardio",
    },
    nav: {
      dashboard: "Dashboard",
      atlas: "Atlas Neural",
      workouts: "Entrenamientos",
      history: "Historial",
      analytics: "Análisis",
      settings: "Ajustes",
      signOut: "Cerrar Sesión",
      level: "Nivel",
    },
    ui: {
      welcome: "Bienvenido",
      efficiency: "Eficiencia Operativa",
      tier: "Operador Nivel 07",
      scanner: "Iniciar Escáner",
      selectMuscle: "Selecciona un grupo muscular del atlas para identificar movimientos compatibles.",
      database: "Accediendo a la Base de Datos...",
      difficulty: "Dificultad",
      search: "Buscar ejercicios...",
      routines: "Rutinas Tácticas",
      viewAll: "Ver Todo",
      intermediate: "Intermedio",
      units: "Unidades",
      min: "Min",
      activeSession: "Sesión Activa",
      formatTime: "registrado",
      payload: "Carga",
      repetitions: "Repeticiones",
      register: "Registrar Rendimiento",
      sessionHistory: "Historial de Sesión",
      telemetry: "Telemetría en Vivo",
      terminate: "Terminar",
      objective: "Objetivo Actual",
      returnBase: "Volver a Base",
      returnCommand: "Volver a Comando",
      anterior: "Anterior",
      posterior: "Posterior",
      musculature: "Musculatura",
      core: "Core",
      equipment: "Equipo",
      selectEquipment: "Seleccionar Equipo Disponible",
      saveSession: "Guardar Sesión",
      discardSession: "Descartar Sesión",
      confirmDiscard: "¿Estás seguro de que deseas descartar esta sesión? Todo el progreso se perderá.",
      deleteConfirm: "¿Estás seguro de que deseas eliminar esta sesión?",
      confirm: "Confirmar",
      cancel: "Cancelar",
    },
    equipment: {
      bodyweight: "Peso Corporal",
      barbell: "Barra",
      dumbbell: "Mancuernas",
      machine: "Máquina / Poleas",
      plate: "Disco",
      bench: "Banco",
      kettlebell: "Pesa Rusa",
      band: "Banda de Resistencia",
      ab_wheel: "Rueda Abdominal",
    },
    stats: {
      recovery: "Recuperación Biométrica",
      intensity: "Intensidad de Sesión",
      load: "Carga Acumulada",
    },
    auth: {
      loginTitle: "Autenticación",
      registerTitle: "Registro de Operador",
      loginDesc: "Acceso seguro a tu inteligencia de entrenamiento.",
      registerDesc: "Inicia tu evolución con la inteligencia de FitAtlas.",
      fullName: "Nombre Completo",
      email: "Enlace de Comunicaciones",
      password: "Clave de Encriptación",
      initiate: "Iniciar Sesión",
      finalize: "Finalizar Registro",
      newOperator: "Registrar Nuevo Operador",
      existingIntel: "Acceder a Intel Existente",
      namePlaceholder: "Nombre del Operador",
      emailPlaceholder: "operador@fitatlas.ai",
    },
    landing: {
      badge: "FitAtlas 2.0 Alpha — Ya Disponible",
      title: "DEJA DE ENTRENAR. EVOLUCIONA.",
      subtitle: "La inteligencia de entrenamiento más sofisticada del mundo. Mapeo muscular bio-visual, análisis de estrés inteligente y progresión inspirada en RPG.",
      getStarted: "Inicia tu Evolución",
      manifesto: "El Manifiesto",
      atlasTitle: "Atlas Neural",
      atlasDesc: "Mapeo muscular biomecánico interactivo para una precisión quirúrgica en el ejercicio.",
      stressTitle: "Motor de Estrés",
      stressDesc: "Cálculos de tensión mecánica en tiempo real y distribución de volumen.",
      rpgTitle: "Progresión RPG",
      rpgDesc: "Nivelación gamificada de atributos y recomendaciones de entrenamiento adaptativas.",
      privacy: "Privacidad",
      terms: "Términos",
      support: "Soporte",
      footer: "Diseñado para el top 1%.",
    },
    about: {
      title: "Entrenando para la Nueva Era.",
      subtitle: "FitAtlas no es solo un rastreador. Es un motor de inteligencia biológica diseñado para cerrar la brecha entre el esfuerzo humano y la precisión algorítmica.",
      dnaTitle: "Nuestro ADN",
      dnaDesc: "Creemos que cada repetición es un dato. Al visualizar la tensión mecánica distribuida en tu anatomía, proporcionamos los conocimientos necesarios para alcanzar la optimización fisiológica máxima.",
      goalTitle: "El Objetivo",
      goalDesc: "Elimina las conjeturas. Ya seas un operador profesional o un entusiasta dedicado, FitAtlas proporciona la hoja de ruta táctica para tu evolución definitiva.",
      pillarsTitle: "Pilares Operativos",
      p1Title: "Integridad",
      p1Desc: "Precisión científica en cada cálculo biomecánico.",
      p2Title: "Eficiencia",
      p2Desc: "Maximizando el rendimiento mientras se optimizan las ventanas de recuperación.",
      p3Title: "Precisión",
      p3Desc: "Aislamiento muscular específico a través de mapeo visual.",
      visionTitle: "Únete a la Élite.",
      visionDesc: "Estamos construyendo el futuro de la inteligencia física. Sé parte de la primera generación de atletas que entrenan con el poder del Atlas.",
      visionBtn: "Inicializar Evolución",
    },
    routines: {
      managerTitle: "Comando Táctico",
      createBtn: "Inicializar Rutina",
      editBtn: "Modificar",
      deleteBtn: "Purgar",
      startBtn: "Iniciar",
      emptyState: "No se identificaron rutinas tácticas. Inicializa tu primer protocolo.",
      editorTitle: "Arquitecto de Protocolo",
      saveBtn: "Guardar Rutina",
      addExercise: "Añadir Objetivo",
      routineName: "Designación de Rutina",
      difficulty: "Nivel de Esfuerzo",
      blocks: "Bloques",
      sets: "Series",
      reps: "Reps",
      weight: "Peso (kg)",
      time: "Tiempo (min)",
      superset: "Protocolo de Superserie",
      restPeriod: "Duración de Descanso",
      restAfterSuperset: "Descanso Post-Superserie",
      addSuperset: "Inicializar Superserie",
      exerciseType: "Modalidad",
    },
    analytics: {
      title: "Inteligencia de Rendimiento",
      subtitle: "Biomecánica de rendimiento y recuperación en tiempo real",
      totalSessions: "Sesiones Totales",
      totalPayload: "Carga Total",
      avgIntensity: "Intensidad Promedio",
      efficiency: "Eficiencia",
      performanceDelta: "Delta de Rendimiento",
      volume: "Volumen",
      insufficientData: "Datos insuficientes para la visualización del rendimiento",
      focusDistribution: "Distribución de Enfoque",
      balanceWarning: "Tu enfoque principal sigue en la cadena anterior. Considera aumentar el volumen posterior para un balance biomecánico.",
      balanceGood: "Tu distribución es equilibrada. Mantén esta proporción para prevenir adaptaciones posturales.",
      recoveryMap: "Mapa de Recuperación Neural",
      recoverySubtitle: "Fatiga muscular estimada basada en el historial de entrenamiento",
      recovered: "Recuperado",
      lightFatigue: "Fatiga Leve",
      moderateFatigue: "Moderada",
      highFatigue: "Fatiga Alta",
      howItWorksTitle: "Cómo funciona",
      howItWorksDesc: "El motor de recuperación calcula la fatiga muscular local usando un modelo de decaimiento exponencial (T½ ≈ 24h). Las sesiones de alta intensidad (RPE 9-10) generan mayor fatiga y requieren ventanas más largas. Entrenar músculos en \"Rojo\" aumenta significativamente el riesgo de lesiones y el agotamiento del SNC.",
    },
    settings: {
      title: "Panel de Control",
      subtitle: "Configura tu perfil de operador y preferencias",
      profile: "Información del Perfil",
      language: "Idioma del Sistema",
      name: "Nombre del Operador",
      email: "Enlace de Comms",
      password: "Nueva Clave de Encriptación",
      currentPassword: "Clave Actual",
      save: "Aplicar Cambios",
      success: "Perfil actualizado correctamente",
      error: "Error al actualizar el perfil",
    },
    difficulty: {
      very_easy: "Muy Fácil",
      easy: "Fácil",
      medium: "Medio",
      hard: "Difícil",
      elite: "Élite",
      epic: "Épico",
    },
    misc: {
      noData: "Sin datos",
      mixedProtocol: "Protocolo Mixto",
    }
  },
};
